# Generated by Django 3.0.8 on 2020-08-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=20)),
                ('number_of_layers', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_net.User')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_number', models.IntegerField(default=0)),
                ('number_of_neurons', models.IntegerField(default=0)),
                ('wieghts', models.CharField(max_length=100000)),
                ('biases', models.CharField(max_length=100000)),
                ('parent_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_net.Network')),
            ],
        ),
    ]
