# Generated by Django 3.0.8 on 2020-08-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_net', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
