# Generated by Django 3.0.8 on 2020-08-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_net', '0002_auto_20200803_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
