# Generated by Django 3.0.3 on 2020-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_net', '0004_auto_20200804_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='wieghts',
            new_name='weights',
        ),
    ]
